### ISSUE TITLE
Can not access property onCaptchaCompleted. 

### ISSUE THREAD

**Issue by ashish8833** [leewinder/ng2-google-recaptcha#13]
Angular Version : 4.3.1
Angular CLI :  1.2.3
ng2-google-recaptcha : 1.2.0

That's good plugins for Google recaptcha. but when I build over angular application, I faced error in terminal. that access private method access out side of the class. 

**Error**

> project_dir/node_modules/ng2-google-recaptcha/create-recaptcha/create-recaptcha.component.ts.CreateRecaptchaComponent.html (2,52): Property 'onCaptchaCompleted' is private and only accessible within class 'CreateRecaptchaComponent

In file create-recaptcha.component.ts at **/node_modules/ng2-google-recaptcha/create-recaptcha/create-recaptcha.component.ts**, that method **onCaptchaCompleted** that access specifier was **private**. 

When I change that access specifier private to public that plugin run perfectly.

That effect on code or not please explain.

Thanks.

**Comment by leewinder** [comment]
Resolved in v5.0.0
https://github.com/leewinder/ng2-google-recaptcha/blob/61bc26800f5879f15d995164b0b2cd06c97697cc/development/src/ng2-google-recaptcha/create-recaptcha/create-recaptcha.component.ts#L55
