### ISSUE TITLE
Cannot find name '__filename'.

### ISSUE THREAD

**Issue by Filip1986** [leewinder/ng2-google-recaptcha#14]
node_modules/ng2-google-recaptcha/create-recaptcha/create-recaptcha.component.ts (10,15): Cannot find name '__filename'.

**Comment by leewinder** [comment]
This is resolved in v5.0.0, just make sure you add @types to your dependencies
https://github.com/leewinder/ng2-google-recaptcha/blob/develop/samples/package.json#L46

**Comment by santhoshrajuvysyaraju** [comment]
I t is giving same issue again in angular 5
