### ISSUE TITLE
Error on first usage of this lib

### ISSUE THREAD

**Issue by cassmtnr** [leewinder/ng2-google-recaptcha#16]
`
Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 194:50 in the original .ts file), resolving symbol NgModule in X:/cdmz/git/morador/node_modules/ng2-google-recaptcha/node_modules/@angular/core/core.d.ts, resolving symbol RecaptchaModule in X:/cdmz/git/morador/node_modules/ng2-google-recaptcha/module/recaptcha.module.ts, resolving symbol RecaptchaModule in X:/cdmz/git/morador/node_modules/ng2-google-recaptcha/module/recaptcha.module.ts
`

**Comment by leewinder** [comment]
Updated to v5.0.0, please check the required dependencies in your project
https://github.com/leewinder/ng2-google-recaptcha/blob/develop/samples/package.json#L17
