### ISSUE TITLE
Getting issue "encountered resolving symbol values statically"

### ISSUE THREAD

**Issue by iamsatyam77** [leewinder/ng2-google-recaptcha#17]
![screenshot from 2017-12-15 18 12 50](https://user-images.githubusercontent.com/34573881/34042649-b1c490e2-e1c3-11e7-84fa-be53507ac398.png)
ERROR in Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 194:50 in the original .ts file), resolving symbol NgModule in /home/vinit/Documents/WorkSpace/OpportunityDealer/OpportunityDealer_R2.0/client/node_modules/ng2-google-recaptcha/node_modules/@angular/core/core.d.ts, resolving symbol RecaptchaModule in /home/vinit/Documents/WorkSpace/OpportunityDealer/OpportunityDealer_R2.0/client/node_modules/ng2-google-recaptcha/module/recaptcha.module.ts, resolving symbol RecaptchaModule in /home/vinit/Documents/WorkSpace/OpportunityDealer/OpportunityDealer_R2.0/client/node_modules/ng2-google-recaptcha/module/recaptcha.module.ts

**Comment by leewinder** [comment]
Please update to v5.0.0 and check your dependencies
https://github.com/leewinder/ng2-google-recaptcha/blob/61bc26800f5879f15d995164b0b2cd06c97697cc/samples/package.json#L44
