### ISSUE TITLE
Random error in Firefox

### ISSUE THREAD

**Issue by Raju-zap** [leewinder/ng2-google-recaptcha#6]
Random issue: grecaptcha.render is not a function error. Due to this sometimes recaptcha was not loading.
I did this to render recaptcha directive instead of simple render 

+            var script = document.createElement('script');
+            script.src = 'https://www.google.com/recaptcha/api.js';
+            script.async = true;
+            script.defer = true;
             var self = this;
+            script.onload = function(){
+                setTimeout(function(){
+                    self.recaptchaRenderElement = grecaptcha.render(recaptchaElement, recaptchaStyle);
+                }, 1000)
             }
+            document.getElementsByTagName('head')[0].appendChild(script);

You can fix and take pull request form Raju-zap for this directive.

**Comment by leewinder** [comment]
Pull request merged and released in v1.2.0
https://www.npmjs.com/package/ng2-google-recaptcha
